### PR TITLE
[#32] Callinperf - create new subtests plus fixup of existing tests

### PR DESCRIPTION
**Pull request by estess**
…in performance changes #32 (callinperf)

New subtests added:

1. environment subtest (replication) - tests new $VIEW("ENVIRONMENT") under various environmental conditions
   such as M-code, trigger, callin and such in both M runtime and update process environments.
2. test_rtn_replace subtest - When a routine is on the stack and is re-linked, zlput_rname() is what looks
   to see if the routine is on the stack or not. But prior to V63002_R110, it was not going back past a call-in
   base frame so if the routine was on the stack prior to that, it was not found and bad things could happen.
   This subtest tests that condition and verifies it works (test fails with a core file prior to V63002_R110).
   Note this test uses VIEW "LINK":"RECURSIVE" but that it not required to encounter the flaw. It just makes
   the flaw easier to detect and cause an issue in a test situation.
3. test_mprof_hidden_rtn subtest - Similar to test_rtn_replace above, M-Profiling also looks back in the stack
   looking for routines to get informating from them. When not found due to being blocked by the call-in base
   frame, the information M-Profiling returns is compromised. Though not as spectacular as a core failure, this
   test too fails on V63002_R110 due to bad information generated.
4. test_ci_z_halt subtest - Pre V63002_R110 versions did a real halt for [Z]HALT commands done in a call-in
   environment. In V63002_R110 this was changed to return to the call-in caller with ZHALT supplying the
   return code. This subtest verifies that the return happens correctly.
5. test_ci_zgoto0 subtest - In V63002_R110 the methodology of the zgoto 0 return was changed. It used to
   unwind back to the call-in base frame and engage the ci_ret_code_exit routine which did a longjmp(). The
   new support in V63002_R110 does not return that way any more. It instead returns to gtm_levl_ret_code
   like all the other returns from call_in routines. This subtest just verifies that is working-as-redesigned.

Files added/changed for new subtests:

call_ins/com/SUITE - add replication invocation for call_ins/environment.

call_ins/inref/drivecirtn.c - Utility external call that drives a call-in routine specified by argument.

call_ins/inref/environci.c - external call that does call-in to environci^environment.

call_ins/inref/environment.m - main driver routine plus callin entry point for $VIEW("ENVIRONMENT") testing.

call_ins/inref/testcizgoto01.m - main driver routine for test_ci_zgoto0 subtest

call_ins/inref/testcizgoto02.m - routine driven by call-in in test_ci_zgoto0 subtest

call_ins/inref/testcizhalt1.m - main driver routine for test_ci_z_halt

call_ins/inref/testcizhalt2.m - routine driven by call-in in test_ci_z_halt that does a HALT

call_ins/inref/testcizhalt3.m - routine driven by call-in in test_ci_z_halt that does a ZHALT

call_ins/inref/testmprofhiddenrtn1.m - main driver routine for test_mprof_hidden_rtn

call_ins/inref/testmprofhiddenrtn2.m - routine driven by call-in in test_mprof_hidden_rtn

call_ins/inref/testrtnreplc1.m - main driver routine for test_rtn_replace

call_ins/inref/testrtnreplc2.m - routine drive by call-in in test_rtn_replace

call_ins/inref/testrtnreplc3.m - Simple routine driven to test that a routine CAN be driven from a replaced routine

call_ins/instream.csh
  1. Add environment subtest to test $VIEW("ENVIRONMENT") in various situations (replication test)
  2. Add test_rtn_replace subtest to verify routine on stack prior to call-in that gets replaced works correctly
  3. Add test_mprof_hidden_rtn subtest to verify routine on stack prior to call-in can be located in M-Profiling
  4. Add test_ci_z_halt subtest to verify [Z]HALT commands return to caller rather than actually halting
  5. Add test_ci_zgoto0 subtest to verify ZGOTO 0 returns to caller properly

call_ins/outref/outref.txt - Add entries for 5 tests added to instream.csh.

call_ins/outref/environment.txt
call_ins/outref/test_ci_z_halt.txt
call_ins/outref/test_ci_zgoto0.txt
call_ins/outref/test_mprof_hidden_rtn.txt
call_ins/outref/test_rtn_replace.txt
  1. Added references files for each of the added tests

call_ins/u_inref/test_ci_z_halt.csh
call_ins/u_inref/test_ci_zgoto0.csh
call_ins/u_inref/test_mprof_hidden_rtn.csh
call_ins/u_inref/test_rtn_replace.csh
call_ins/u_inref/environment.csh
  1. Added driver scripts for each of the new tests
  Note: Once changes are made such that call-ins can be done in TP, the environment test should be modified to
  drive the same external call we currently drive only on the primary side that then does a call back in and drives
  $VIEW("ENVIRONMENT").

Files modified for previous subtests:

call_ins/inref/divzro.m
call_ins/inref/divzro2.m
call_ins/inref/divzro3.m
call_ins/inref/divzro4.m
call_ins/inref/dvzrozt.m
call_ins/inref/dvzrozt2.m
call_ins/inref/dvzrozt3.m
call_ins/inref/dvzrozt4.m
  1. All of the above M routines were modified to get info for stack level 0 instead of stack
     level 1 due to callins now starting with a stack level 1 lower than previously.

call_ins/inref/gtmxc_test_types.c
  1. Converted to use gtm_cip() instead of gtm_cp() for one test to see if it changed anything.

call_ins/outref/c_args.txt
call_ins/outref/gtm_args.txt
  1. Reduce levels by one due to level start change with this project.

call_ins/outref/gtm_exit_err.txt
  1. Reduce levels by one due to level start change with this project.
  2. Modified to get info for stack level 0 instead of stack level 1 due to callins now starting
     with a stack level 1 lower than previously.

call_ins/outref/maxnstlvl.txt
  1. Remove GTM$CI stack level
  2. Add full stack and new call in level entry indicator.

call_ins/outref/nest_err.txt
call_ins/outref/nest_err_et.txt
call_ins/outref/nest_err_et2.txt
call_ins/outref/nest_err_et3.txt
call_ins/outref/nest_err_zt.txt
call_ins/outref/nest_err_zt2.txt
call_ins/outref/nest_err_zt3.txt
  1. Reduce levels by one due to level start change with this project.
  2. Modified to get info for stack level 0 instead of stack level 1 due to callins now starting
     with a stack level 1 lower than previously.

call_ins/u_inref/ctomctom.csh
call_ins/u_inref/ctomtom.csh
  1. Correct the unsetenv statements to not include the '$' of the envvar being unset.

inref/gtm8431.m
  - Remove references to GTM$CI and variations as it is nothing special now.

outref/gtm8431.txt
  - Remove output related to GTM$CI as it no longer exists.

Modified the environment subtest to use generalized drivecirtn instead of its subtest-specific call-in driver.

Disable MPROF tracing from the test system as that interfers with the test_mprof_hidden_rtn subtest

General changes to retrofit new subtests to new T63000A base. Also fixed all the statements of the
sort "unsetenv $envvar" which should of course not have the '$' in it. Fixing these introduced some
errors in some tests so the unsetenv was moved to the end of the test where it should be.

### CODE REVIEW

**Comment by nars1** [comment]
Forgot to mention this. Thanks for the detailed commit comment. It made the review a  breeze.

**Comment by estess** [comment]
Reivew replies - done here as I cannot reply directly to these comments like I can with comments in code:

1. Done
1. Done
1. I've reworded this comment to be more clear that these changes were due to the rebase BACK to T63000A (this commit was done this week).
1. Done
1. Done

For the following comment: "I notice all possibilities except MUPIP,TRIGGER,CALLIN are tested. Is this missed out because it is not straightforward?".

The answer is that in the MUPIP environment, the only runtime is in a TRIGGER which is by definition TP currently preventing a CALLIN from happening. Once call-ins support TP in some fashion, this will be possible but not until then.

**Comment by estess** [comment]
Note - dismissing review as only changes requested were to the commit message itself.

**Comment by nars1** [comment]
I am fine with the responses. Just close this pull request and open a new one with the revised commit comment.

**Comment by estess** [comment]
Closing this pull request (unmerged) to open a new one with an updated commit message.

**Pull request closed without merging**
